baseURL = "https://disproserv.com.ar"
title = "Disproserv"
author = "disproserv"
languageCode = "es"
DefaultContentLanguage = "es"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]
  showBlog = false # hide blog, as we won't use it
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo_disproserv.svg"
    alt = "Disproserv Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Disproserv"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Disproserv es una empresa de ingeniería cuya experiencia le permite abordar con éxito casi cualquier proyecto de carácter industrial."
    meta_og_title = "Disproserv"
    meta_og_type = "website"
    meta_og_url = "https://disporserv.com.ar"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Disproserv es una empresa de ingeniería cuya experiencia le permite abordar con éxito casi cualquier proyecto de carácter industrial."

[menu]

  [[menu.main]]
    identifier = "servicios"
    name = "Servicios"
    url = "/servicios/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Acerca"
    url = "/acerca/"
    weight = 3

  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    url = "/contacto/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Inicio"
    url = "/"
      weight = 1